### PR TITLE
Minimal changes to support wrapping of igraph

### LINKED ISSUE #129: LoadError: No CLType translation available for: CLType
I'm trying to wrap a major system library Xcb.h.
(Files in https://gist.github.com/lobingera/ec5ee777f459eb923972)

1: running w_xcb.h stopps with 

```
WARNING:   incorrect typesize for Unexposed field
WARNING: Skipping unnamed UnionDecl
WARNING: Skipping unnamed UnionDecl
WARNING: Skipping unnamed UnionDecl
WARNING: Skipping unnamed StructDecl
INFO: Error thrown. Last cursor available in Clang.wrap_c.debug_cursors
ERROR: LoadError: No CLType translation available for: CLType (Clang.cindex.Invalid) 
 in repr_jl at /home/lobi/.julia/v0.4/Clang/src/wrap_c.jl:287
 in wrap at /home/lobi/.julia/v0.4/Clang/src/wrap_c.jl:350
 in wrap_header at /home/lobi/.julia/v0.4/Clang/src/wrap_c.jl:649
 in run at /home/lobi/.julia/v0.4/Clang/src/wrap_c.jl:790
 in include at ./boot.jl:252
 in include_from_node1 at ./loading.jl:134
 in process_options at ./client.jl:310
 in _start at ./client.jl:409
while loading /home/lobi/juliarepo/gen_testing/w_xcb.jl, in expression starting on line 23
```

after a lot of warnings.

The debug cursor points to

```
julia> Clang.wrap_c.debug_cursors
1-element Array{Clang.cindex.CLCursor,1}:
 CLCursor (Clang.cindex.FunctionDecl) sched_yield()
```

2: Preprocessing the xbc.h with 

```
clang -E /usr/include/xcb/xcb.h > x1.h
```

and running w_x1.jl stopps with same error message.

### LINKED ISSUE #176: KeyError: key 119 not found
Running Clang.jl (master) on a relatively large C codebase, I keep getting the following error:
```
INFO: Error thrown. Last cursor available in Clang.wrap_c.debug_cursors
ERROR: LoadError: KeyError: key 119 not found
 in getindex(::Dict{Int32,Any}, ::Int32) at ./dict.jl:688
 in getTypedefDeclUnderlyingType(::Clang.cindex.TypedefDecl) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/cindex/base.jl:91
 in #wrap#35(::String, ::Function, ::Clang.wrap_c.WrapContext, ::DataStructures.OrderedDict{Symbol,Clang.wrap_c.ExprUnit}, ::Clang.cindex.TypedefDecl) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:501
 in wrap(::Clang.wrap_c.WrapContext, ::DataStructures.OrderedDict{Symbol,Clang.wrap_c.ExprUnit}, ::Clang.cindex.TypedefDecl) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:478
 in wrap_header(::Clang.wrap_c.WrapContext, ::Clang.cindex.TranslationUnit, ::String, ::Array{Any,1}) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:680
 in run(::Clang.wrap_c.WrapContext) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:799
```

Not sure how to proceed... Any direction would be appreciated!

### PR DESCRIPTION
**Pull request by jgoldfar**
Definitely closes #176, may also close #129 (since I saw the same message and subsequently added `cindex.Invalid` to `cl_to_jl` list.) Fix one deprecation warning on v0.5 as well.

### CODE REVIEW

File: src/cindex.jl [hunk 1]
```diff
@@ -221,7 +221,11 @@ endof(tl::TokenList) = length(tl)
 done(tl::TokenList, i) = (i > length(tl))
 
 function getindex(tl::TokenList, i::Int)
-    if (i < 1 || i > length(tl)) throw(BoundsError()) end
+    if (i < 1 || i > length(tl))
+        # throw(BoundsError())
+        warn("TokenList miss at index ", i)
+        return Comment(string("TokenList miss at index ", i))
```
Comment (jgoldfar) [inline src/cindex.jl]: @ihnorton I'm particularly unsure about this change... I definitely needed it, but it seems pretty underhanded.

Comment (ihnorton) [inline src/cindex.jl]: Do you happen to have a backtrace when that happened? My guess would be wrap_c.jl:606 -- the logic there should probably check whether returned `pos` is over the length and avoid trying to index.

This change isn't going to break anything, but it might hide some preprocessor stuff that wouldn't have been processable anyway (the lexer is extremely minimal, just enough to handle `#define` constants and basic expressions, so it bails out and prints everything a comment).

Comment (jgoldfar) [inline src/cindex.jl]: I managed to find it.
```
INFO: Error thrown. Last cursor available in Clang.wrap_c.debug_cursors
ERROR: LoadError: BoundsError
 in getindex(::Clang.cindex.TokenList, ::Int64) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/cindex.jl:224
 in handle_macro_exprn(::Clang.cindex.TokenList, ::Int64) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:575
 in wrap(::Clang.wrap_c.WrapContext, ::DataStructures.OrderedDict{Symbol,Clang.wrap_c.ExprUnit}, ::Clang.cindex.MacroDefinition) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:606
 in wrap_header(::Clang.wrap_c.WrapContext, ::Clang.cindex.TranslationUnit, ::String, ::Array{Any,1}) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:681
 in run(::Clang.wrap_c.WrapContext) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:800
```

Comment (ihnorton) [inline src/cindex.jl]: I found the problem. Will merge this plus some other fixes this weekend. Thanks!
